name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test:headless

    - name: Build
      run: npm run build:prod -- --base-href /

    - name: Compress Files
      run: zip -r app.zip dist/knitter/*

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: app.zip
